# Site settings
email: contact@stellarium.org
description: >-
  Stellarium is a planetarium software that shows exactly what you see when you look up at the stars. It's easy to use, and free.
keywords: >-
  Stellarium, planetarium, astronomy, software, stars, planets, constellations, meteors, universe, open source, free software,
  astro, freeware, download, stars, planets, realistic, software, sky, program, scientific, educational, free, real, time,
  Windows, Linux, Apple, Mac, GPL, milky way, moon, mercury, venus, mars, earth, venus, jupiter, saturn, sun, real time, 3D,
  openGL, graphic, GL, chart, map, twinkle, photo-realistic, brightness, screenshot
baseurl: ""

lang: en

wiki_url: https://github.com/Stellarium/stellarium/wiki

google_analytics: UA-109850660-1

langnames:
  af: Afrikaans
  ar: ‫العربية‬'
  az: Azərbaycan dili
  be: Беларуская
  bg: български
  bn: বাংলা
  bs: Bosanski
  ca: Català
  ca@valencia: Català (Valencià)
  cs: česky
  de: Deutsch
  el: Ελληνικά
  en: English
  en_CA: English (Canada)
  en_GB: English (United Kingdom)
  en_IN: English (India)
  eo: Esperanto'
  es: Español
  et: Eesti keel
  eu: Euskara
  fa: فارسی
  fi: Suomen
  fr: Français
  gd: Gàidhlig
  gl: Galego
  hr: Hrvatski
  hrx: Hunns-rikk
  hu: Magyar nyelv
  id: Bahasa Indonesia
  is: íslenska
  it: Italiano
  ja: 日本語
  ka: ქართული ენა
  ko: 한국어/조선말
  ky: Кыргызча
  la: Latin
  lb: Lëtzebuergesch
  lv: Latviešu valoda
  lt: lietuvių kalba
  ms: Bahasa Melayu
  nb: Norsk bokmål
  nl: Nederlands
  pl: Polski
  pt: Português
  pt_BR: Português (Brazil)
  ro: Română
  ru: Pусский
  sc: Sardu
  sk: Slovenčina
  sq: Gjuha shqipe
  sr: Српски
  sv: Svenska
  te: తెలుగు
  th: ภาษาไทย
  tl: Tagalog
  tr: Türkçe
  uk: Yкраїнська
  ug: Uyƣurqə
  vi: Tiếng Việt  
  zh_CN: 简体中文 (中国)
  zh_HK: 繁體中文 (香港)
  zh_TW: 正體中文 (臺灣)

doc_versions: [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, "0.20", 0.21, 0.22, "1.x", 23.0, 24.0]

doc_plugin_versions: [0.14]

version: 24.4
series: "24.0"
next_version: 25.1
guide_base_version: 24.4
guide_version: 24.4-1
doi: 10.5281/zenodo.14543500

posts: 15

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-github-metadata

collections:
  i18n:
    output: true
    permalink: /:path
  scripts:
    output: true
  landscapes-interplanetary:
    output: true
  landscapes-africa:
    output: true
  landscapes-asia:
    output: true
  landscapes-australasia:
    output: true
  landscapes-europe:
    output: true
  landscapes-north-america:
    output: true
  landscapes-south-america:
    output: true
  landscapes-polar:
    output: true
  landscapes-special:
    output: true
  skycultures:
    output: true
  scenery3d-collection:
    output: true

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - po/
  - utils/

keep_files:
  - doc/
  - doc-plugins/
  - pkgdiff/
  - img/

include:
  - .well-known
